### ISSUE TITLE
Waddy's texture list viewport not fit to window resizing

### ISSUE THREAD

**Issue by G2Pavon** [khanghugo/gchimp#1]
![image](https://github.com/khanghugo/gchimp/assets/14117486/21b31ccb-d703-4c23-9d36-cefe0402c659)

**Comment by khanghugo** [comment]
At the moment I just hard code grid count. I am still vastly unfamiliar with egui framework to do something truly flexible.

**Comment by khanghugo** [comment]
Fixed per 7e0c139
