### ISSUE TITLE
[Waddy] Add support for .bsp files

### ISSUE THREAD

**Issue by G2Pavon** [khanghugo/gchimp#13]
Basically, extract textures from bsp. But the idea is to display the textures first and then the user chooses what to do, whether to save as wad, extract selected textures or do nothing just view them.

**Comment by khanghugo** [comment]
give 2ea3291c1c98bc23c3f062e0e6f66ca64e2a8934 a try and see. Wait like a few minutes for CI to finish then you can have the version
