### ISSUE TITLE
[Waddy] Show recent wads

### ISSUE THREAD

**Issue by G2Pavon** [khanghugo/gchimp#14]
when click Menu

![image](https://github.com/user-attachments/assets/b052a0c4-a1c3-496c-b978-ae50ca64ceea)

**Comment by khanghugo** [comment]
Hmmm this might need persistent storage. I guess it staying in config.toml directory is fine

**Comment by khanghugo** [comment]
Should work as of c046ad0142ed8638dded0c7badea26e285b2a305
