### ISSUE TITLE
Avoid using egui::Grid for texture grid

### ISSUE THREAD

**Issue by khanghugo** [khanghugo/gchimp#17]
Right now, it goes like this:

ScrollArea covers a very huge Grid. ScrollArea could just be the grid. The problem with that is ScrollArea can efficiently render only visible rows while Grid is rendered as whole. So, ScrollArea for a Grid means the Grid renders as whole and the Grid is ONE ROW. So, Grid is always visible so ScrollArea cannot un-visit it. This means a WAD with thousands of textures will have thousands of rendered texture.

I have tried doing the easy way, which is just removing the Grid and it looks like this.
![image](https://github.com/user-attachments/assets/91633cb0-3179-4739-9931-aafbc933ba08)

Any attempt to change texture_tile seems like too much of work.

**Comment by khanghugo** [comment]
Interesting. Putting a grid inna row. This is totally relevant. I guess that will work. I was trying out the show rows earlier but I didn't try it with grid. Feel free to make a PR.

The only reason that I use grid is that the UI is consistent and very organized. I could not get rid of it because of screenshot above.

**Comment by khanghugo** [comment]
show_row() is efficient for displaying data because it will know not to render things not visible on surface.

**Comment by khanghugo** [comment]
LOL I just realize this is the same code I have but show_rows instead of show and that works. Interesting.

**Comment by G2Pavon** [comment]
i need to find a way to make the transitions between rendered and non-rendered rows smooth when scrolling. Currently the behavior feels like "snap to grid"


https://github.com/user-attachments/assets/3749fcb2-7da3-4909-afec-99adc4092694

```rust 
    fn texture_grid(&mut self, ui: &mut Ui, instance_index: usize) {
        let image_tile_size =
            BASE_IMAGE_TILE_SIZE * ui.ctx().options(|options| options.zoom_factor);
        let texture_per_row = ((ui.min_size().x / image_tile_size).floor() as usize).max(4);
        let row_height = image_tile_size;

        let count = self.instances[instance_index].texture_tiles.len();
        let is_search_enabled = self.instances[instance_index].search.enable;
        let search_text = self.instances[instance_index].search.text.to_lowercase();

        let filtered_tiles: Vec<usize> = (0..count)
            .filter(|&texture_tile| {
                if is_search_enabled {
                    self.instances[instance_index].texture_tiles[texture_tile]
                        .name
                        .to_lowercase()
                        .contains(search_text.as_str())
                } else {
                    true
                }
            })
            .collect();

        let total_filtered_tiles = filtered_tiles.len();
        let total_rows = (total_filtered_tiles + texture_per_row - 1) / texture_per_row;

        ScrollArea::vertical()
            .max_height(total_rows as f32 * row_height) // prevents glitch when continue scrolling on the last row
            .drag_to_scroll(false)
            .show_rows(ui, row_height, total_rows, |ui, row_range| {
                egui::Grid::new("waddy_grid")
                    .num_columns(texture_per_row)
                    .spacing([2.0, 2.0])
                    .show(ui, |ui| {
                        for row in row_range {
                            for col in 0..texture_per_row {
                                let texture_index = row * texture_per_row + col;
                                if texture_index < total_filtered_tiles {
                                    let texture_tile_index = filtered_tiles[texture_index];
                                    self.texture_tile(
                                        ui,
                                        instance_index,
                                        texture_tile_index,
                                        image_tile_size,
                                    );
                                }
                            }
                            ui.end_row();
                        }
                    });
            });
    }```

**Comment by khanghugo** [comment]
Maybe you got the height wrong. It is `2. + 36 + (BASE_IMAGE_TILE_SIZE * zoom_factor)`

**Comment by G2Pavon** [comment]
` 2. + 36 + (BASE_IMAGE_TILE_SIZE * zoom_factor)`  works
thanks

**Comment by khanghugo** [comment]
Yea, the explanation is that:
`2.` is margin
`36.` is `18. * 2` and that is the clickable labels.
Each texture tile is affected by `zoom_factor` as the first line of the function suggests so you have to multiply `BASE_IMAGE_TILE_SIZE` by `zoom_factor`.

**Comment by khanghugo** [comment]
I took the liberty to make the changes myself in 6fb302b850922bc5648eee7b5c3da3ae6435953b

So far no problems on my end so I guess that works.
