### ISSUE TITLE
Panning zoom affects the entire interface

### ISSUE THREAD

**Issue by G2Pavon** [khanghugo/gchimp#2]
Current behavior `CTRL` + `+` & `CTRL` + `-`:

[Screencast from 01-07-24 21:12:27.webm](https://github.com/khanghugo/gchimp/assets/14117486/495203cb-308a-4f80-9315-8dee1b80df3c)

Maybe it's better if pan zoom only affects Waddy's texture list viewport instead of the entire ui/others tools. Reference:

https://github.com/khanghugo/gchimp/assets/14117486/2ffac7f9-1bbf-43f4-a3d7-2eda11111416

**Comment by khanghugo** [comment]
If you zoom in the app, everything would zoom in. But now the zoom will also scale the texture tiles in Waddy accordingly per d8c7b19
