### ISSUE TITLE
[Waddy] Allow multiple selection

### ISSUE THREAD

**Issue by G2Pavon** [khanghugo/gchimp#4]
Also would also be nice if there was a marker indicating which texture is selected.

**Comment by khanghugo** [comment]
Multiple selection for what use case? I was thinking about drag and drop from one window to another but so far it is not trivial to implement. Maybe you are referring to something else because I am not sure just selecting lots of texture does. Exporting multiple texture files?

**Comment by G2Pavon** [comment]
for export and delete

**Comment by khanghugo** [comment]
added in 3ec1c234b48a74eaafbc45fadb1ccfc622ef6c81
