### ISSUE TITLE
Add search bar + sorting in Waddy

### ISSUE THREAD

**Issue by phayzeeVW** [khanghugo/gchimp#9]

**Comment by khanghugo** [comment]
I like search bar but I am not so sure about sorting. Sorting seems redundant unless the softwares interpreting WAD file don't sort it themselves. I find that finding texture through filtering is good enough. Sorting just makes things fairly more confusing (eg: I want to know which texture I just added recently).

**Comment by khanghugo** [comment]
Search bar is added as of acbebf55378a79e28f21bc45001b7b78f05ab50b
